In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from '/Users/shreyaggarwal/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>

In [4]:
lst = [2,3,4]

In [5]:
lst

[2, 3, 4]

In [6]:
arr = np.array([12,12,34])

In [7]:
arr

array([12, 12, 34])

In [8]:
arr[0]

12

In [15]:
m_arr  = np.array([[1,2,3],[2,3,4]], dtype = 'int8')

In [16]:
m_arr

array([[1, 2, 3],
       [2, 3, 4]], dtype=int8)

In [12]:
m_arr[0][0]

1

In [13]:
m_arr.shape

(2, 3)

In [17]:
m_arr.dtype

dtype('int8')

# creating numpy array using lists

In [18]:
m_arr  = np.array([[1,2,3],[2,3,4]], dtype = 'int8')

In [31]:
z_arr = np.zeros((1))

In [32]:
z_arr

array([0.])

In [34]:
o_arr = np.ones((3,4))

In [35]:
o_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
arra = np.arange(10)

In [38]:
arra

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
lspace = np.linspace(1,5,100)

In [46]:
lspace

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [60]:
em = np.empty((2,10))

In [61]:
em

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [62]:
emp_like = np.empty_like((lspace))

In [63]:
emp_like

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [64]:
id = np.identity(45)

In [65]:
id

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [66]:
id.shape

(45, 45)

In [67]:
ln_ar = np.arange(10)

In [68]:
ln_ar 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
ln_ar.shape

(10,)

In [75]:
re_ar = ln_ar.reshape(2,5)

In [76]:
re_ar

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
or_ = re_ar.ravel() 

In [79]:
or_

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
two_dim  = np.array([[1,2],[0,3]]) 


In [82]:
two_dim

array([[1, 2],
       [0, 3]])

In [84]:
two_dim.sum(axis = 0)

array([1, 5])

In [88]:
x = np.array([[1,2,3],[4,5,6],[7,1,0]])

In [89]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [90]:
x.sum(axis = 0 )

array([12,  8,  9])

In [91]:
x.sum(axis = 1 )

array([ 6, 15,  8])

In [93]:
y = x.T

In [94]:
y

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [95]:
y.flat

In [96]:
for i in y.flat:
    print(i)

1
4
7
2
5
1
3
6
0


In [97]:
y.ndim

2

In [98]:
y.size

9

In [99]:
y.nbytes

72

In [100]:
one = np.array([1,3,4,56,2])


In [101]:
one.argmax()

3

In [102]:
one.argmin()

0

In [103]:
one.argsort() 

array([0, 4, 1, 2, 3])

In [107]:
y

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [108]:
y.argmax(axis=0)

array([2, 2, 0])

In [109]:
y.argmax(axis=1)

array([2, 1, 1])